# -*- coding: utf-8 -*-
"""A090H334.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BaoLeAb_WbSfzh3KLpdeMtZQE5x6jx5Q

# HASH 雜湊函數
1005
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo howareyou > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo Howareyou > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt